drop table DPET1;

CREATE TABLE DPET1
(DEPTNO NUMBER,
 DNAME VARCHAR2(100),
 CONSTRAINT DPET1_PK PRIMARY KEY (DEPTNO ) 
 );
 
INSERT INTO DPET1 (DEPTNO,DNAME)
VALUES (1,'HR DEPT');
INSERT INTO DPET1 (DEPTNO,DNAME)
VALUES (2,'PO DEPT');
COMMIT;

SELECT  * FROM DPET1;

drop table emp1;

CREATE TABLE EMP1
( EMPID NUMBER PRIMARY KEY,
  ENAME VARCHAR2(100),
  DEPTNO NUMBER,
  CONSTRAINT EMP1_FK FOREIGN KEY (DEPTNO) REFERENCES DPET1(DEPTNO) ON DELETE CASCADE
);

INSERT INTO EMP1 VALUES (1, 'khaled','1');
INSERT INTO EMP1 VALUES (2, 'ali','1');
INSERT INTO EMP1 VALUES (3, 'ahmed','1');
INSERT INTO EMP1 VALUES (4, 'rania','2');
INSERT INTO EMP1 VALUES (5, 'lara','2');
COMMIT;

SELECT * FROM EMP1;

DELETE FROM DPET1
WHERE DEPTNO=1;

SELECT * FROM EMP1;

create or replace trigger EMP1_t
before
delete
on EMP1
for each row
declare
minv number;
begin
    select min(EMPID)
    into minv
    from emp1;
end;
    

DELETE FROM DPET1
WHERE DEPTNO=2;








